version: 0.0.1.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
max_jobs: 4
image: Visual Studio 2017
configuration: Release
platform:
- x64
- Win32
clone_folder: c:\projects\audio-router
nuget:
  disable_publish_on_pr: true
build:
  project: c:\projects\audio-router\audio-router.sln
  verbosity: minimal
artifacts:
- path: '\bin\Release\x64'
  name: Release_x64
- path: '\bin\Release\Win32'
  name: Release_Win32
